http redirects function
denoland/saaskit pull request #131
Opened 2023-04-28 07:24 UTC by andrewdelanoy

#91 
Created redirect helper function, updated redirects in existing code to use function.

Only changed one redirect to put the user on the sign up page rather than login, those could probably still be looked at.

2023-04-28 09:16 UTC, iuioiua requested changes
Thanks for helping out, @andrewdelanoy! Could you please address my requests? Also, could you please:
1. Clean up any code commented out from this PR.
2. Ensure the HTTP status codes are correct according to each scenario? This was my main concern and what I ignored when implementing redirects as a whole.
3. Revert any changes that don't pertain to the primary purpose of this PR - HTTP redirects.

Thanks!

2023-04-28 09:16 UTC, iuioiua commented on utils/redirect.ts
Are you able to:
1. Rename this file to `http.ts`?
2. Use the function signature outlined in the original issue (#91)? `redirect(path: string, status: 300 | 301...) => Response`
3. `body` can be `null`

2023-04-28 09:16 UTC, iuioiua commented on twind.config.ts
Are you able to revert these changes?

2023-04-28 09:16 UTC, iuioiua commented on routes/login/index.tsx
> +            </a>
Can you pleas revert this change?

2023-04-28 09:16 UTC, iuioiua commented on routes/account/manage.ts
> +import { RedirectHelper } from "../../utils/redirect.ts";
Can you please import from "@/utils/redirect.ts"?

2023-04-28 09:23 UTC, andrewdelanoy commented
I will address all the changes you mentioned!

2023-05-02 04:43 UTC, iuioiua commented
I've just fixed a couple of merge conflicts. Please let me know if there's anything else I can help with.

2023-05-04 22:28 UTC, iuioiua commented
Hi @andrewdelanoy, I'd like to implement this in the next few days. If you cannot do so, are you happy for me to take this one? 🙂

2023-05-05 04:23 UTC, huai-jie commented
> 2. Ensure the HTTP status codes are correct according to each scenario? This was my main concern and what I ignored when implementing redirects as a whole.

Referencing https://deno.land/std@0.182.0/http/http_status.ts?source#L252 could be helpful.

2023-05-09 05:34 UTC, iuioiua commented
This has been superseded by #163. I appreciate your help either way, @andrewdelanoy!

2023-05-09 05:34 UTC, closed without merging