Themes
denoland/saaskit pull request #219
Opened 2023-05-20 01:21 UTC by load1n9

2023-05-21 01:18 UTC, iuioiua requested changes
I'm really excited about this! Are you also able to update the following elements:
1. Comment input on item page
2. Inputs on submit page
3. Buttons on hover state

2023-05-21 01:18 UTC, iuioiua commented on routes/index.tsx
> +        />
I believe this script is unnecessary if we just want to support the system's theme preference.

2023-05-21 01:18 UTC, iuioiua commented on components/Layout.tsx
> +      } dark:text-white`}
Are you able to move this next to the other hardcoded classes? It would look a little cleaner.

2023-05-21 01:18 UTC, iuioiua commented on components/Layout.tsx
> +      } dark:text-gray-300`}
Ditto

2023-05-21 01:21 UTC, iuioiua commented
I think it's worth trying to use `...gray-500` where possible. It may not need to change between light and dark modes.

2023-05-21 02:27 UTC, load1n9 commented
> I'm really excited about this! Are you also able to update the following elements:
> 
> 1. Comment input on item page
> 2. Inputs on submit page
> 3. Buttons on hover state

sure thing

2023-05-24 01:14 UTC, iuioiua commented on .vscode/settings.json
Please revert these changes

2023-05-24 01:16 UTC, iuioiua commented on utils/constants.ts
> +  "px-4 py-2 bg-pink-700 text-white text-lg rounded-lg border-2 border-pink-700 transition duration-300 disabled:(opacity-50 cursor-not-allowed) light:(hover:(bg-white text-pink-700)) dark:(hover:bg-
```suggestion
  "px-4 py-2 bg-pink-700 text-white text-lg rounded-lg border-2 border-pink-700 transition duration-300 disabled:(opacity-50 cursor-not-allowed) light:(hover:(bg-white text-pink-700)) dark:(hover:bg-pink-800 text-white)";
```

2023-05-24 01:17 UTC, iuioiua commented
> > I'm really excited about this! Are you also able to update the following elements:
> > 
> > 1. Comment input on item page
> > 2. Inputs on submit page
> > 3. Buttons on hover state
> 
> sure thing

I'll merge once these 3 and my recent suggestions are fixed 😄

2023-06-05 00:53 UTC, iuioiua approved these changes
I've gone ahead and made some tweaks to this. Thanks for the help, @load1n9! It's looking really nice.

2023-06-05 00:53 UTC, merged