Avatar Images on Profile Page
denoland/saaskit pull request #220
Opened 2023-05-21 00:30 UTC by zzeleznick

## Description
This PR adds the current user's avatar image on the `/account` page.

**Addresses** https://github.com/denoland/saaskit/issues/213

### Adds
- User avatar image

### Removes
- Unused reset password logic

### Visual Diff
| Before | After |
| -- | -- |
| <img width="1298" alt="Screen Shot 2023-05-20 at 5 25 40 PM" src="https://github.com/denoland/saaskit/assets/5779832/3667cbb1-8e3a-4ac5-b356-2925504130c9"> | <img width="1366" alt="Screen Shot 2023-05-20 at 5 26 27 PM" src="https://github.com/denoland/saaskit/assets/5779832/04143b9a-7811-4ee9-88e5-8761799214d2"> |

2023-05-21 08:22 UTC, iuioiua requested changes
Thanks, @zzeleznick. I'm not too sold on the exact current design. I have two design ideas:
1. Delete the "Account"
2. Or make the avatar image as small as 2 lines and put it next to the username row.
WDYT?

2023-05-21 16:52 UTC, zzeleznick commented
@iuioiua  – I'm also not sold on the current user profile page design, but I opted with your first suggestion as I feel like option (2) where the profile image is in-line with the username is more of a mobile design (using Github's profile page as a reference)/

| Github Profile Normal | Mobile View |
| -- | -- |
| <img width="975" alt="Screen Shot 2023-05-21 at 9 48 28 AM" src="https://github.com/denoland/saaskit/assets/5779832/ff654123-5c26-4ed7-8f6f-139bb2d7422e"> | <img width="376" alt="Screen Shot 2023-05-21 at 9 48 41 AM" src="https://github.com/denoland/saaskit/assets/5779832/5625d006-03b0-4bc8-80bb-dcd764b3392d"> |

I also added in the user's name but I can remove it if you'd prefer.

2023-05-22 00:20 UTC, iuioiua commented
Let's omit the user's name for now. Removing the "Account" heading should suffice.

2023-05-22 01:48 UTC, zzeleznick commented
@iuioiua  – updated

2023-05-22 02:02 UTC, iuioiua approved these changes
Please note: including the user display name at this point would've required a database reset. While we have to reset the database occasionally, I'm trying to keep it to a minimum.

Either way, my ugly avatar image is looking very nice. And nice cleanup with the reset password stuff. LGTM! Thank you.

2023-05-22 02:02 UTC, merged

2023-05-22 02:03 UTC, iuioiua commented on routes/account/index.tsx
> +            crossOrigin="anonymous"
Good enough for now.