proposal: user pages
denoland/saaskit pull request #229
Opened 2023-05-24 21:54 UTC by brunocorrea23

https://github.com/denoland/saaskit/issues/181

2023-05-24 22:36 UTC, iuioiua requested changes
You're heading in the right direction! However, the page I had in mind had an avatar image and username at the top, aligned vertically or horizontally (whichever looks and feels nicer). The rest of the page would be a feed of the items by that user, using a new `getItemsByUser()` in `/utils/db.ts` and using `<ItemSummary />`.

Please let me know if you need any help with anything.

2023-05-24 22:36 UTC, iuioiua commented on routes/user/[username].tsx
> +    });
```suggestion
    return ctx.render({ ...ctx.state, user });
```

2023-05-24 22:36 UTC, iuioiua commented on routes/user/[username].tsx
> +import { BUTTON_STYLES, NOTICE_STYLES } from "@/utils/constants.ts";
```suggestion
```

2023-05-24 22:36 UTC, iuioiua commented on routes/user/[username].tsx
> +      <Head title="User" href={props.url.href} />
```suggestion
      <Head title={props.data.user.login} href={props.url.href} />
```

2023-05-25 22:44 UTC, brunocorrea23 commented
nvm, already included the new getItemsByUser() in /utils/db.ts and also added the items to the user page

2023-05-25 22:54 UTC, iuioiua approved these changes
This is 🔥

We can de-duplicate some of the shared code between the user page and the home page in a follow-up PR. Thank you, @brunocorrea23.

2023-05-25 22:54 UTC, merged