feat: pagination on the item page for comments + time-ago filter
denoland/saaskit pull request #257
Opened 2023-06-08 23:51 UTC by brunocorrea23

#212 
#211

2023-06-09 03:05 UTC, iuioiua commented
Are you able to confirm whether this solves #256?

2023-06-09 09:45 UTC, brunocorrea23 commented
In a way, yes. This PR allows for the user to add more than 10 comments in an item if you maintain PAGE_LENGTH=10.

But the core of the issue is still not solved.
It seems that the issue is connected to the Kv.getMany function on the getManyUsers function. It seems that the Kv.getMany function can't handle an array with more than 10 items as an input. (are you able to confirm if this is a limitation of the getMany function in kv?).

So if you slice the pages in groups of 10 elements (items, comments, etc) or less, you should be fine. But if you change PAGE_LENGTH to 20, for example, it throws an error. This is true not only for the items page, but also for the home page.

2023-06-12 03:46 UTC, iuioiua commented
Yes, `PAGE_LENGTH` should not increase beyond 10 because of this current limitation in Deno KV.

2023-06-12 04:00 UTC, iuioiua requested changes
Sorry for the delay in the review. I've given it a quick read and left some suggestions.

2023-06-12 04:00 UTC, iuioiua commented on routes/index.tsx
> +    <div class="flex justify-center">
Please add a note above saying these links do not preserve current URL queries. E.g. if `?page=2`, that'll be removed once one of these links is clicked. This behaviour is fine in this particular context but might need to change in the future as more URL queries control the item list view.

2023-06-12 04:00 UTC, iuioiua commented on routes/item/[id].tsx
>  }
Can we centralise and de-duplicate any pagination-related code in the utils folder with accompanying tests?

2023-06-12 04:00 UTC, iuioiua commented on routes/item/[id].tsx
> +const PAGE_LENGTH = 10;
Please add a short explainer regarding why this should not exceed 10. Perhaps, there's a GitHub issue in the main https://github.com/denoland/deno repo that could be referenced also.

2023-06-17 08:19 UTC, iuioiua commented
Hi @brunocorrea23, just checking in. Are you still happy to pursue this PR?

2023-06-18 13:27 UTC, brunocorrea23 commented
Hey! Yes. Will tackle this today. Couldn't take a look over the week, sorry.

2023-06-19 05:54 UTC, iuioiua approved these changes
Pretty much LGTM! I think it might be best positioned above the item list, though. WDYT?

2023-06-19 22:24 UTC, iuioiua approved these changes
Awesome! LGTM! Thank you, @brunocorrea23.

2023-06-19 22:24 UTC, merged