fix: charts not responsive
denoland/saaskit pull request #259
Opened 2023-06-13 15:36 UTC by huai-jie

close https://github.com/denoland/saaskit/issues/251

Before
![image](https://github.com/denoland/saaskit/assets/58794979/2bfea801-0ea8-4fd8-80aa-5ab044ec8405)

After
![image](https://github.com/denoland/saaskit/assets/58794979/631b54d6-408d-4689-b235-16a45060779f)

2023-06-13 23:26 UTC, iuioiua requested changes
Can we insert the new class in a `<style>` in the `<Head />` for the stats page only? We should also note somewhere that this is a workaround for [Fresh Charts not being responsive](https://github.com/denoland/fresh_charts/issues/11).

2023-06-13 23:26 UTC, iuioiua commented on static/app.css
Could this instead be a `<style>` in the `<Head />` for just the stats page?

2023-06-17 08:17 UTC, iuioiua commented
Sorry, @huai-jie. To clarify, I'm happy to merge this PR, as long as we note that it's a workaround.

2023-06-17 09:04 UTC, huai-jie commented
> Can we instead insert the new class in a `<style>` in the `<Head />` for the stats page? We should also note somewhere that this is a workaround for [Fresh Charts not being responsive](https://github.com/denoland/fresh_charts/issues/11). I've made a suggestion for that issue.

done it

2023-06-18 00:20 UTC, iuioiua approved these changes
LGTM! Thank you, @huai-jie!

2023-06-18 00:21 UTC, merged