fix: remove type assertions, fix code
denoland/saaskit pull request #264
Opened 2023-06-17 23:30 UTC by nicu-chiciuc

## Adding types
Fixes https://github.com/denoland/saaskit/issues/261

I started by adding
```
// @deno-types="npm:stripe"
```
just above the `Stripe` import.
This is based on https://deno.com/manual@v1.34.0/advanced/typescript/types#providing-types-when-importing

This is not the best solution, but currently there's an issue with having types for Stripe in Deno: 
https://github.com/stripe-samples/stripe-node-deno-samples/issues/2

## Covering all possibilities
After the initial error was fixed, I was receiving a different error, also caused by type assertions, so I had to change
```
pricePerInterval={toPricePerInterval(
                product.default_price as Stripe.Price,
              )}
```
and handle all cases

## Testing
1. `git clone ...`
2. `deno task start`
3. access http://localhost:8000/pricing
4. you shouldn't see a 500 error

<img width="773" alt="Screenshot 2023-06-18 at 02 29 37" src="https://github.com/denoland/saaskit/assets/4076804/b50d1d77-e324-40a2-980e-58e8561216a9">

          
<img width="1481" alt="Screenshot 2023-06-18 at 02 28 30" src="https://github.com/denoland/saaskit/assets/4076804/3380e1a9-5808-4125-ae60-9e5c9bfccaad">

## PS
`defaultPrice.recurring?.interval` already has a defined type, but I wasn't sure what's the correct way to import it in Deno. I left it as string since it's not a critical part of the app, it's used just for displaying text. So it's not a high-concern at the moment.

2023-06-18 15:57 UTC, nicu-chiciuc commented
What should https://github.com/denoland/saaskit/pull/264/commits/cd476cdb302e1b9d35b8fd26c504637dd1e6a423 accomplish?

2023-06-22 01:13 UTC, iuioiua requested changes
My main thought is that the checks added in this PR aren't needed if the `init:stripe` task is run correctly. So having `product.default_price` as `Stripe.Price` is acceptable. If `product.default_price` is not of type `Stripe.Price`, we may have to investigate the `init:stripe` task, as it's not working correctly.

Either way, nice work fixing the Stripe types! I've added a suggestion to improve this situation for the whole codebase.

2023-06-22 01:13 UTC, iuioiua commented on utils/payments.ts
> +// @deno-types="npm:stripe"
Can you move this to a `stripe.ts` file at the root of this codebase and point the `stripe` import in the `import_map.json` to that file? That way, all files that import `stripe` also get types.

Also, can you please add a version that ensures the types and runtime versions of `stripe` match?

2023-06-23 07:44 UTC, nicu-chiciuc commented
I see, in that case a better solution would've been for me to not make these checks but throw a custom error/banner instead of relying on type assertions. That means I could remove most of the code checks.

2023-06-23 07:51 UTC, iuioiua commented
Yes, I'd rather the code threw 👍🏾

2023-07-01 13:41 UTC, nicu-chiciuc commented
I'm made the changes. Remove the type assertions and threw and error (had to create a type guard for this to work).

I still get an error on the pricing page, even after running `deno task init:stripe` since one of the elements in `data` doesn't have a `default_price`. But that's consistent with the previous implementation.

2023-07-01 14:23 UTC, nicu-chiciuc commented
I've also moved the stripe definitions into `stripe.ts`. I had to change import in `stripe-webhooks.ts` so it uses a default export like all the other files.

2023-07-02 07:13 UTC, iuioiua approved these changes
I made a few fixes, and now LGTM! Thanks for this!

Note for future: please use `deno task ok` before `git push`-ing to ensure all checks pass.

2023-07-02 07:13 UTC, merged