feat: rating algorithm
denoland/saaskit pull request #359
Opened 2023-07-10 08:44 UTC by roberto-morado

This commit reflects the changes made after reviewing and incorporating feedback.

2023-07-10 21:49 UTC, iuioiua requested changes
Looking better. Few tweaks are needed.

2023-07-10 21:49 UTC, iuioiua commented on utils/db.ts
> +    .set(itemsByUserKey, newItemsByUserRes)
Can you please ensure all operations in this function happen on the same atomic operation (below)?

2023-07-10 21:49 UTC, iuioiua commented on utils/db.ts
> +export function compareRank(a: Item, b: Item): number {
```suggestion
export function compareRating(a: Item, b: Item): number {
```

2023-07-10 21:49 UTC, iuioiua commented on utils/db.ts
> +): number {
```suggestion
export function calcRating(item: Item): number {
```

2023-07-11 18:59 UTC, roberto-morado commented
This will also resolve #209

2023-07-11 22:06 UTC, iuioiua requested changes
Looking much better! One thing left. Can you please modify `deleteComment()` to match `createComment()`?

2023-07-12 00:18 UTC, iuioiua commented
Oh, I almost forgot - can you please modify `migrateKv()` to update current items with their respective `itemCount`s?

2023-07-12 04:15 UTC, roberto-morado commented
> Oh, I almost forgot - can you please modify `migrateKv()` to update current items with their respective `itemCount`s?

What is the purpose of this script?

Is it because items already in the database do not contain the `commentsCount` property?

So I would have to count the number of comments in an item and update the value accordingly?

2023-07-12 04:20 UTC, iuioiua commented
Yes and yes 🙂

2023-07-14 19:58 UTC, roberto-morado commented
> Oh, I almost forgot - can you please modify `migrateKv()` to update current items with their respective `itemCount`s?

I have a question regarding the migrate_kv.ts file; it would appear that the item ids are hard coded, I'll assume that those are the items that are currently in the prod. database, however it would appear that there exist more that 13 items on the prod. db (website). Would you like me to not touch the ids and only work on updating their key-values?... which in this case I'll be adding the commentsCount property to the item.

2023-07-14 23:25 UTC, iuioiua commented
The migration script is used whenever there's a change in the database structure. The script, in its current state, has already been run. You can mould it however you'd like now, including removing those item IDs.

2023-07-19 06:20 UTC, iuioiua commented
Did you need a hand with the migration script?

2023-07-20 03:30 UTC, iuioiua commented
I've been reconsidering this feature. I'm not entirely convinced that the value it adds, if any, outweighs the added complexity.

Happy to others' thoughts.
CC @mbhrznr, @lino-levan, @brunocorrea23

2023-07-20 04:23 UTC, lino-levan commented
I'm pretty neutral on this. I'm not a fan or complexity but this is a nice feature. Up to you and the others.

2023-07-20 05:03 UTC, brunocorrea23 commented
Yeah.. I agree with you. I'm not so sure about it now.
When I created #234 , I believe we were only sorting by votes, which is bad because very old and irrelevant post might appear first. But now that we have the filters for last week, last month and all time, this becomes less of a problem.

I still think that #209 is a nice feature as it indicates how 'hot' is the topic. If we sliced it only to this issue, would you still think that the value outweighs the complexity?

2023-07-20 05:20 UTC, iuioiua commented
Yeah, I like the comment count aspect, but the algorithm functionality may not be needed.

2023-07-20 06:11 UTC, mbhrznr commented
as @brunocorrea23 already mentioned, having the filters available reduces the need for the algorithm quite a bit.

however the sorting algorithm itself doesn't seem too complicated, does it?
if we'd slice it to only account for the item's comment count, we'd need the migration and the added complexity in item creation (and deletion) anyway, wouldn't we?

or would we try to find another approach on how to integrate the comment count?

2023-07-20 07:08 UTC, iuioiua commented
The implementation of the sorting algorithm is straightforward. It's more the algorithm design that could become tedious. For example, why do the weight coefficients have those values in particular? There isn't a clear objective reason why they would use any given values for this use case (Deno Hunt).

The aim is to have items the user likes more likely to appear at the top. Genuinely, IDK that such a solution is that much better than just using votes.

I can see the comments count as helping with that a bit.

> if we'd slice it to only account for the item's comment count, we'd need the migration and the added complexity in item creation (and deletion) anyway, wouldn't we?

Yep, that's right. But it may be worth it.

2023-07-20 07:09 UTC, iuioiua commented
It seems it'll be fine to skip the algorithm functionality on this change, @roberto-morado. However, having the item's comments count is still a good idea.

2023-07-20 07:58 UTC, roberto-morado commented
Understood.

Also; I apologize for the late response, I became quite busy at my day job this past week.

Let me know if there is anything else I can help with. I love the app, I'd like to contribute more.

2023-07-23 00:57 UTC, closed without merging