feat: disallow duplicate entries for users
denoland/saaskit pull request #447
Opened 2023-08-26 15:13 UTC by mbhrznr

closes #377.  

this disallows users from submitting duplicate entries.  
upon submission all user entries are checked for uniqueness on either `title` or `url`.

2023-08-26 15:40 UTC, mbhrznr commented
`/submit` already has some checks in place, yet we always return an empty response with status `400`.
would it make sense to return more distinct responses in terms of status and (potentially) message?

2023-08-26 23:21 UTC, iuioiua commented
Yep! I think a [HTTP 409 status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) with a concise text body message would be fitting 👍🏾

2023-08-29 00:37 UTC, iuioiua requested changes

2023-08-29 00:37 UTC, iuioiua commented on routes/submit/index.tsx
> +      return new Response("URL or Title are either invalid or missing.", {
```suggestion
      return new Response("Item URL or title are either invalid or missing.", {
```

2023-08-29 00:37 UTC, iuioiua commented on routes/submit/index.tsx
> +        return new Response("URL must be valid and publicly available.", {
```suggestion
        return new Response("Item URL must be valid and publicly available.", {
```

2023-08-29 00:37 UTC, iuioiua commented on routes/submit/index.tsx
> +      return new Response("An Error occurred while validating the URL.", {
```suggestion
      return new Response("An error occurred while validating the URL.", {
```

2023-08-29 00:37 UTC, iuioiua commented on routes/submit/index.tsx
> +    if (!user) {
```suggestion
    if (user === null) {
```

2023-08-29 00:37 UTC, iuioiua commented on routes/submit/index.tsx
> +      return new Response("You must be logged in to submit a new Item.", {
```suggestion
      return new Response("You must be logged in to submit a new item.", {
```

2023-08-29 00:37 UTC, iuioiua commented on routes/submit/index.tsx
> +        "You already submitted an Item which contains the same Title or URL.",
```suggestion
        "You already submitted an item which contains the same title or URL.",
```

2023-08-29 00:41 UTC, iuioiua approved these changes
I've made some tweaks, and now, LGTM! Thanks, Michael 🙏🏾

2023-08-29 00:41 UTC, merged